{% set name = "consumer" %}
{% if os.getenv('PROVIDER') %}
{%   set provider = "provider" + os.environ['PROVIDER'] %}
{% else %}
{%   set provider = None %}
{% endif %}

{% set use_features = not os.getenv('NO_FEATURES') %}
{% if use_features or not provider %}
{% set build = 1 %}
{% else %}
# earlier build has no features
{% set build = 0 %}
{% endif %}

package:
  name: {{ name }}
  version: 1.0.0

build:
  number: {{ build }}
  script: touch $PREFIX/{{ name }}
  {% if use_features %}
  features:
    - {{ provider }}
  {% endif %}

requirements:
  {% if provider %}
  run:
    - {{ provider }}
  {% endif %}
