{% set name = "provider" + os.environ['PROVIDER'] %}
{% set use_features = not os.getenv('NO_FEATURES') %}
{% set use_meta = False %}
{% if use_features %}
{% set build = 1 %}
{% else %}
# earlier build has no features
{% set build = 0 %}
{% endif %}
package:
  name: {{ name }}
  version: 1.0.0

build:
  number: {{ build }}
  script: touch $PREFIX/{{ name }}
  {% if use_features %}
  {% if use_meta %}
  features
  {% else %}
  track_features:
  {% endif %}
    - {{ name }}
  {% endif %}

{% if use_features and use_meta %}
requirements:
  run:
    - meta * {{ name }}
{% endif %}
